
title: Ewan Gardner-Young Portfolio
email: Ewan8gy@icloud.com
description: >- # this means to ignore newlines until "baseurl:"
  I am a games programmer currently studying computer games applications development in my 4th year at abertay unviersity, below you can find some of the projects I have worked on!
domain: "ewangy.github.io"
url: "https://justegg1.github.io/ewangy.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  JustEgg1
remote_theme: anxhe/jekyll-theme-experiment

jekyll-theme-experiment:
  about: # optional
    avatar: https://media.licdn.com/dms/image/v2/D4E03AQFcelpFBzQs2A/profile-displayphoto-shrink_800_800/B4EZQOI7aDGcAc-/0/1735404010164?e=1761177600&v=beta&t=64JY7w1lhNbF96XaOssr2mpOjgXgqqtQrUD9vIxfQsg

  portfolio: # optional
    title: Projects
    # Depending of the number of projects, you will need to update $projects
    # variable in a sass file. e.g.
    # _sass/main.scss
    #
    projects:
      - name: University Professional Project
        link: /2025/09/22/welcome-to-jekyll/
        github: https://goopling-games.itch.io/chronicles-of-marten
        img_relative_url: https://img.itch.zone/aW1nLzIwODY0OTQ0LnBuZw==/original/WDa2Gk.png

      - name: Unreal Engine Mechanics Project  
        link: /2025/09/22/welcome-to-jekyll.html
        github: https://github.com/JustEgg1/Coursework-CMP302
        img_relative_url: https://i.imgur.com/mc0rRaK.png

# Build settings
#theme: jekyll-theme-experiment
plugins:
  - jekyll-feed
  
